/* autogenerated by mkparser - DO NOT EDIT */

#include "esekey.h"

char*
parse(struct input_event ev)
{

	if (ev.type == EV_KEY && ev.value == 1) {

		switch (ev.code) {

			/* Keys with keykodes < 111 are useless for Funkey
			   because they are present on all keyboards
			   (e.g. letters, numbers, ENTER, SHIFT, other) */

			case 111:
				return "DELETE";
			case 112:
				return "MACRO";
			case 113:
				return "MUTE";
			case 114:
				return "VOLUMEDOWN";
			case 115:
				return "VOLUMEUP";
			case 116:
				return "POWER";
			case 117:
				return "KPEQUAL";
			case 118:
				return "KPPLUSMINUS";
			case 119:
				return "PAUSE";
			case 120:
				return "F21";
			case 121:
				return "F22";
			case 122:
				return "F23";
			case 123:
				return "F24";
			case 124:
				return "KPCOMMA";
			case 125:
				return "LEFTMETA";
			case 126:
				return "RIGHTMETA";
			case 127:
				return "COMPOSE";
			case 128:
				return "STOP";
			case 129:
				return "AGAIN";
			case 130:
				return "PROPS";
			case 131:
				return "UNDO";
			case 132:
				return "FRONT";
			case 133:
				return "COPY";
			case 134:
				return "OPEN";
			case 135:
				return "PASTE";
			case 136:
				return "FIND";
			case 137:
				return "CUT";
			case 138:
				return "HELP";
			case 139:
				return "MENU";
			case 140:
				return "CALC";
			case 141:
				return "SETUP";
			case 142:
				return "SLEEP";
			case 143:
				return "WAKEUP";
			case 144:
				return "FILE";
			case 145:
				return "SENDFILE";
			case 146:
				return "DELETEFILE";
			case 147:
				return "XFER";
			case 148:
				return "PROG1";
			case 149:
				return "PROG2";
			case 150:
				return "WWW";
			case 151:
				return "MSDOS";
			case 152:
				return "COFFEE";
			case 153:
				return "DIRECTION";
			case 154:
				return "CYCLEWINDOWS";
			case 155:
				return "MAIL";
			case 156:
				return "BOOKMARKS";
			case 157:
				return "COMPUTER";
			case 158:
				return "BACK";
			case 159:
				return "FORWARD";
			case 160:
				return "CLOSECD";
			case 161:
				return "EJECTCD";
			case 162:
				return "EJECTCLOSECD";
			case 163:
				return "NEXTSONG";
			case 164:
				return "PLAYPAUSE";
			case 165:
				return "PREVIOUSSONG";
			case 166:
				return "STOPCD";
			case 167:
				return "RECORD";
			case 168:
				return "REWIND";
			case 169:
				return "PHONE";
			case 170:
				return "ISO";
			case 171:
				return "CONFIG";
			case 172:
				return "HOMEPAGE";
			case 173:
				return "REFRESH";
			case 174:
				return "EXIT";
			case 175:
				return "MOVE";
			case 176:
				return "EDIT";
			case 177:
				return "SCROLLUP";
			case 178:
				return "SCROLLDOWN";
			case 179:
				return "KPLEFTPAREN";
			case 180:
				return "KPRIGHTPAREN";
			case 181:
				return "INTL1";
			case 182:
				return "INTL2";
			case 183:
				return "INTL3";
			case 184:
				return "INTL4";
			case 185:
				return "INTL5";
			case 186:
				return "INTL6";
			case 187:
				return "INTL7";
			case 188:
				return "INTL8";
			case 189:
				return "INTL9";
			case 190:
				return "LANG1";
			case 191:
				return "LANG2";
			case 192:
				return "LANG3";
			case 193:
				return "LANG4";
			case 194:
				return "LANG5";
			case 195:
				return "LANG6";
			case 196:
				return "LANG7";
			case 197:
				return "LANG8";
			case 198:
				return "LANG9";
			case 200:
				return "PLAYCD";
			case 201:
				return "PAUSECD";
			case 202:
				return "PROG3";
			case 203:
				return "PROG4";
			case 205:
				return "SUSPEND";
			case 206:
				return "CLOSE";
			case 220:
				return "UNKNOWN";
			case 224:
				return "BRIGHTNESSDOWN";
			case 225:
				return "BRIGHTNESSUP";
			case 511:
				return "MAX";

		}

	}

	return NULL;

}

