name: esekeyd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: bootstrap
        run: sh bootstrap
      - name: configure
        run: sh configure
      - name: clean
        run: make clean
      - name: make
        run: make
